version: '3.3'

services:
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    security_opt:
      - no-new-privileges
    devices:
      - /dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - $HOME/docker/zerotier/data:/var/lib/zerotier-one
    ports:
      - 9993:9993
    environment:
      - PUID=1000
      - PGID=1000
